### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by Numkil** [frodefi/bower-main#2]
Hey frodefi, 

I've been using this plugin for some time and it's been working on my linux laptop perfectly. Lately though I've got some new colleagues who work on windows and there it doesn't seem to do anything. It doesn't crash or report anything, but it also doesn't generate the expected files.

Is this an issue you have encountered already?

This is the bower-main part of my gulpfile.js

``` javascript
var bowerMain = require('bower-main');

var bowerMainJavaScriptFiles = bowerMain('js', 'min.js')
var bowerMainCssFiles= bowerMain('css', 'min.css')

gulp.task('bower', function() {
  return gulp.src(bowerMainJavaScriptFiles.normal)
    .pipe(concat('vendor-scripts.js'))
    .pipe(gulp.dest('web/bundles/global/vendor'));
});

gulp.task('bowerprod', function(){
  return merge2(
    gulp.src(bowerMainJavaScriptFiles.minified),
    gulp.src(bowerMainJavaScriptFiles.minifiedNotFound)
      .pipe(concat('tmp.min.js'))
      .pipe(uglify())
    )
    .pipe(concat('vendor-scripts.js'))
    .pipe(gulp.dest('web/bundles/global/vendor'));
});

gulp.task('bowercss', function() {
  return gulp.src(bowerMainCssFiles.normal)
    .pipe(concat('vendor-styles.css'))
    .pipe(gulp.dest('web/bundles/global/vendor'));
});

gulp.task('bowercssprod', function(){
  return merge2(
    gulp.src(bowerMainCssFiles.minified),
    gulp.src(bowerMainCssFiles.minifiedNotFound)
      .pipe(concat('tmp.min.css'))
      .pipe(uglify())
    )
    .pipe(concat('vendor-styles.css'))
    .pipe(gulp.dest('web/bundles/global/vendor'));
});

```

**Comment by frodefi** [comment]
Hi, @Numkil, I have not tried it on windows, but I could check it out. Unfortunately I have only next week.

**Comment by Numkil** [comment]
There is no hurry in my case, do not worry.

**Comment by Numkil** [comment]
Update; The plugin does work on windows, apparently my co-workers had a brain fart and reported the error falsely to me. I tried it out myself now and there were no problems except for the fact that windows is terribly unsuited for this kind of work. Sorry for the trouble.

**Comment by frodefi** [comment]
Oh, I am glad :) Hope it was not smelly! No trouble, happy somebody is
actually using my thing :)
