### ISSUE TITLE
Not getting all expected css files.

### ISSUE THREAD

**Issue by Numkil** [frodefi/bower-main#5]
For some reason not all the expected css files are found. In my current setup, bower-main misses the css files for bootstrap and only returns the ones from Datatables. I believe it might be due to the underlying bower-main-files but I can't tell with certainity. 

These are my bower.json and gulpfile.js

``` json
   "ignore": [
        "**/.*",
        "node_modules",
        "bower_components",
        "test",
        "tests"
    ],
    "dependencies": {
        "bootstrap": ">=3.1.1",
        "jquery": ">=2.1.0",
        "DataTables": ">=1.10.7",
        "bootbox": ">=4.4.0"
    }
}
```

``` javascript
var bowerMainCssFiles = bowerMain('css', 'min.css');

gulp.task('bowercss', function() {                                                                 
     return gulp.src(bowerMainCssFiles.normal)                                                        
       .pipe(concat('vendor-styles.css'))                                                             
       .pipe(gulp.dest('web/bundles/global/vendor'));                                                 
 });    
```

**Comment by Numkil** [comment]
Might be important to add that .js extensions work without a problem.

**Comment by Numkil** [comment]
It also worked previously but since I did a npm update it doesn't work anymore.

**Comment by frodefi** [comment]
I have not updated bower-main for 4 months.

But I see that the Bootstrap bower-file defines this:

``` json
"main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
```

So it it correct that css is not returned here. But css is available in the package, so perhaps it is a feature request to ignore the bower main definition and try to see if the css file is present? I could do that, but it would take a little a couple of week. I am totally rebuilding the module but stopped halfway because I am extremely busy these days.

**Comment by Numkil** [comment]
Ok thanks for informing me. I wasn't sure just how this plugin worked. Now I can keep this restriction in mind. I think it would be a cool feature to allow users to explicitly ask for their files but the way it works now makes sense, I just didn't know about it.

**Comment by frodefi** [comment]
No problem :) I will include this feature in the next version.

**Comment by leocaseiro** [comment]
Sorry, I'd like to know if this feature is implemented. Otherwise, that would be nice leaving the issue open. So we could send some pull requests.

Thanks

**Comment by frodefi** [comment]
Hi!

I will come back to you in the weekend regarding this

**Comment by leocaseiro** [comment]
Nice! Thanks
